name: textformfield_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  http: ^0.12.1
  image_picker: ^0.6.6+1
  flutter_neumorphic: ^3.1.0
  intl: ^0.17.0
  animated_text_kit: ^4.2.1
  cloud_firestore: ^0.14.1+2
  firebase_core:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true